name: release

on:
  push:
    branches:
      - main

jobs:
  generate_token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.gentoken.outputs.token }}

    steps:
      - name: Generate token
        id: gentoken
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

  tagpr:
    runs-on: ubuntu-latest
    needs: [generate_token]
    outputs:
      tag: ${{ steps.tagpr.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install aqua
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v2.8.0

      - name: Run tagpr
        id: tagpr
        run: tagpr
        env:
          GITHUB_TOKEN: ${{ needs.generate_token.outputs.token }}

  release:
    runs-on: ubuntu-latest
    needs: [tagpr,generate_token]
    if: needs.tagpr.outputs.tag != ''
    outputs:
      tag: ${{ steps.tagpr.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install aqua
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v2.8.0

      - name: Get tag
        run: git pull --tags

      - name: Run goreleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ needs.generate_token.outputs.token }}
