name: test

on:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install aqua
        uses: aquaproj/aqua-installer@v2.3.2
        with:
          aqua_version: v2.23.1

      - name: Run golangci-lint
        run: golangci-lint run

  status-check:
    runs-on: ubuntu-latest
    needs: [lint]
    if: failure()

    steps:
      - name: Fail
        run: exit 1
