name: test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Install aqua
        uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v2.12.2

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run golangci-lint
        run: golangci-lint run

  status-check:
    runs-on: ubuntu-latest
    needs: [lint]
    if: ${{ always() }}

    steps:
      - name: Fail
        if: needs.lint.result == 'failure'
        run: exit 1
