name: test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install aqua
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v2.8.0

      - name: Set up Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version-file: go.mod
          cache: true

      - name: Run golangci-lint
        run: golangci-lint run
